#!/bin/bash
# THIS IS CRITCIAL FOR TEST FAILURES TO REGISTER (stupid bash)
set -e

# -Qwarn catches warnings about integer division
time python -Qwarn -m pytest -n 8 --boxed --timeout=1200 --junitxml=test_unit_results.xml
